#! /bin/sh

set -e

if ! id -u e2guardian > /dev/null 2>&1 ; then
    adduser --system --group \
	--disabled-login \
	--gecos "e2guardian User" \
	--home /var/log/e2guardian \
	--shell /bin/sh \
	e2guardian
fi

e2guardian_user=`grep daemonuser /etc/e2guardian/e2guardian.conf|grep -v '^\ *#' \
	|awk -F = '{print $2}'|tr -d \ \'`

e2guardian_group=`grep daemongroup /etc/e2guardian/e2guardian.conf|grep -v '^\ *#' \
	|awk -F = '{print $2}'|tr -d \ \'`

logdir=`grep loglocation /etc/e2guardian/e2guardian.conf|grep -v '^\ *#' \
	|awk -F = '{print $2}'|tr -d \ \'|xargs -r dirname 2>/dev/null`

echo "$logdir"
test -z "$e2guardian_user" && e2guardian_user=e2guardian
test -z "$e2guardian_group" && e2guardian_group=e2guardian
test -z "$logdir" && logdir=/var/log/e2guardian

chown -R $e2guardian_user:$e2guardian_group $logdir
chmod -R u+wr $logdir
chmod u+wrx $logdir

init_failed ()
{
	echo "WARNING: Starting e2guardian failed. Please check your configuration."
}

#DEBHELPER#
